List<String> motivationalQuotes = [
  '''"Believe in yourself; you've overcome challenges before and will again."''',
  '''"Have faith in your resilience; you've conquered adversity."''',
  '''"You're stronger than you think; trust in your ability to endure."''',
  '''"You've faced storms and emerged stronger; keep believing in yourself."''',
  '''"You've navigated rough waters; have confidence in your journey."''',
  '''"In your strength, you'll find the power to persevere."''',
  '''"Trust in your inner strength; it's carried you through tough times."''',
  '''"Your past triumphs are a testament to your future success."''',
  '''"You're a survivor; keep that faith in your abilities."''',
  '''"You're a warrior, and warriors always rise."''',
  '''"Resilience is your superpower; use it to face what's ahead."''',
  '''"Every challenge you've conquered has prepared you for this moment."''',
  '''"Believe in yourself, for you are your greatest ally."''',
  '''"Your track record of resilience speaks for itself."''',
  '''"You've endured, and you'll continue to thrive."''',
  '''"Trust your journey; it's made you who you are."''',
  '''"You're a survivor; have faith in your strength."''',
  '''"Your strength has carried you through, and it will again."''',
  '''"Through adversity, you've discovered your true strength."''',
  '''"You've faced mountains and moved them; keep climbing."''',
  '''"Believe in yourself; you've overcome obstacles before, and you'll conquer whatever lies ahead."''',
  '''"You've faced challenges and emerged stronger every time. Trust in your resilience."''',
  '''"Your past victories prove you have the strength to triumph over future adversity."''',
  '''"Have faith in your abilities; you're the hero of your own story."''',
  '''"You're a survivor; embrace the uncertainty of the future with confidence."''',
  '''"Trust your journey; you've weathered storms and can handle whatever comes next."''',
  '''"In your history of overcoming, find the confidence to face what's to come."''',
  '''"Your strength is in your survival; let it guide you through any storm."''',
  '''"Every battle you've fought has prepared you for the battles you'll face."''',
  '''"You've endured and thrived; keep that spirit alive in the face of new challenges."''',
  '''"You're a survivor, and survivors find a way to thrive."''',
  '''"Trust the process; you've proven your resilience time and again."''',
  '''"Never doubt your ability to navigate the unknown; your strength is your compass."''',
  '''"Embrace the uncertainty; your past has equipped you for whatever's ahead."''',
  '''"You're a warrior; keep moving forward with courage and determination."''',
  '''"The challenges you've faced are stepping stones to a brighter future."''',
  '''"Have faith in your journey; you've already conquered many mountains."''',
  '''"Your story is one of resilience; let it be your guide to the future."''',
  '''"Believe in yourself; you've already shown how strong you can be."''',
  '''"Trust your instincts; they've led you through darkness into the light."''',
  '''"Challenges are the sparks that ignite personal growth."''',
  '''"In adversity, we find the seeds of our greatest growth."''',
  '''"Welcome challenges as stepping stones on your path to self-improvement."''',
  '''"Every challenge is an invitation to evolve and become better."''',
  '''"Embrace difficulties, for within them lie the lessons that shape you."''',
  '''"Your capacity to grow is directly proportional to your willingness to face challenges."''',
  '''"Don't fear challenges; they are the soil in which your potential flourishes."''',
  '''"See obstacles as opportunities for inner transformation."''',
  '''"Growth thrives in the face of adversity; don't shy away from it."''',
  '''"Challenges are the forge where your character is tempered."''',
  '''"The more you confront challenges, the more you become capable of greatness."''',
  '''"Life's challenges are the sculptor's tools that shape your destiny."''',
  '''"Embrace difficulties with open arms, and you'll emerge stronger and wiser."''',
  '''"Challenge yourself, for that's where the magic of personal growth happens."''',
  '''"In every obstacle, there's a hidden opportunity to become your best self."''',
  '''"Challenges are the fuel that propels you toward your full potential."''',
  '''"The path to self-discovery is paved with the stones of challenges."''',
  '''"When challenges arise, view them as invitations to level up."''',
  '''"Embrace the storm, for it is the rain that makes you grow."''',
  '''"Your journey of growth is illuminated by the light of challenges."''',
  '''"Challenges are the stepping stones to success; embrace them and keep climbing."''',
  '''"In every challenge, there's a chance for growth waiting to be seized."''',
  '''"See challenges as gifts that force us to search for a new center of gravity. Don't fight them. Just find a different way to stand." - Oprah Winfrey''',
  '''"Difficulties in life are intended to make us better, not bitter."''',
  '''"Embrace challenges, for they are the architects of your growth."''',
  '''"Don't fear the storm; learn to dance in the rain."''',
  '''"Opportunities often disguise themselves as challenges."''',
  '''"The harder the battle, the sweeter the victory. Embrace the challenge."''',
  '''"Challenges are the fuel for your personal growth journey."''',
  '''"Each obstacle you face is a chance to level up in life's game."''',
  '''"When faced with a challenge, look for the opportunity within it."''',
  '''"Welcome adversity as a teacher; it will guide you to new heights."''',
  '''"Embrace the struggle; it's where character and growth are forged."''',
  '''"Challenges are your call to adventure on the path of self-discovery."''',
  '''"Opportunity often knocks softly amidst the noise of challenges."''',
  '''"The path to success is paved with the bricks of challenges."''',
  '''"Adversity reveals your true potential; let it be your guide."''',
  '''"Life's challenges are the chisels that shape us into masterpieces."''',
  '''"Don't avoid challenges; seek them out and embrace the lessons they bring."''',
  '''"Growth comes from pushing through difficulties, not avoiding them."''',
  '''"Life's journey may not always be a straight road, but staying grounded helps you navigate the curves."''',
  '''"In the twists and turns of life's path, find your footing and stay true to your course."''',
  '''"When life gets curvy, it's your roots that keep you steady."''',
  '''"Stay grounded in the storms of life, and you'll weather any curve with grace."''',
  '''"Life's unpredictability is what makes your grounded presence even more valuable."''',
  '''"Embrace the curves in life's road; they reveal your resilience."''',
  '''"When life zigzags, let your inner strength be your compass."''',
  '''"In the turbulence of life's journey, remain grounded like a mighty tree."''',
  '''"Stay centered when life spirals; that's when your true strength shines."''',
  '''"The bends in life's path are where you discover your inner stability."''',
  '''"Life's deviations are opportunities to prove your balance and resilience."''',
  '''"When the road twists unexpectedly, your grounded spirit becomes your guide."''',
  '''"Root yourself deep, so even life's sharpest curves won't uproot you."''',
  '''"Life's meandering path is a chance to show your unshakable foundation."''',
  '''"Stay rooted in your values as you navigate the winding roads of life."''',
  '''"The curves in life's journey are where you learn to dance with uncertainty."''',
  '''"In life's labyrinth, staying grounded is your compass to find your way."''',
  '''"Let the twists and turns of life be a reminder to anchor yourself in purpose."''',
  '''"When life takes you on a detour, your grounded spirit is your best guide."''',
  '''"Stay grounded, for it's in the curves that you truly find your strength."''',
  '''"Life's path may be winding, but your inner strength can be your steady compass."''',
  '''"In the twists and turns of life, find your balance and stay true to yourself."''',
  '''"Stay rooted in your values as you navigate life's unpredictable journey."''',
  '''"Life's curves are where you discover your resilience; embrace them."''',
  '''"When life takes unexpected turns, let your core values be your guideposts."''',
  '''"Life's twists are opportunities to show your strength and flexibility."''',
  '''"The road of life may bend, but your resolve can remain unwavering."''',
  '''"Stay centered in the storm of life's uncertainties."''',
  '''"In the meandering river of life, anchor yourself with your principles."''',
  '''"Keep your feet on the ground as life's path takes unexpected detours."''',
  '''"Life's unpredictability is where your true character shines."''',
  '''"When life gets curvy, hold onto your inner peace and navigate with grace."''',
  '''"Let life's curves be your playground for growth and learning."''',
  '''"Stay grounded, even when the road of life seems to twist and turn endlessly."''',
  '''"Life's twists are opportunities to show your resilience and adaptability."''',
  '''"Amidst life's curves, find your center and move forward with purpose."''',
  '''"Your strength is revealed in how you handle life's unexpected bends."''',
  '''"Life's journey is an adventure; embrace the scenic detours."''',
  '''"When life takes you off course, your core values keep you on track."''',
  '''"Stay steady as life's path unfolds; you are the captain of your journey."''',
];
